version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports: [ "6333:6333" ]
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build: ./backend
    env_file: ./backend/.env.example
    depends_on: [ qdrant, redis ]
    ports: [ "8000:8000" ]
    volumes:
      - ./data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379
      - ENABLE_SELF_TRAINING=true
      - FEEDBACK_COLLECTION_ENABLED=true
      - TEMPERATURE=0.7
      - MIN_CONFIDENCE_THRESHOLD=0.8

  frontend:
    build: ./frontend
    depends_on: [ backend ]
    ports: [ "80:80" ]
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  qdrant_data:
  redis_data:
