version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports: [ "6333:6333" ]
    volumes:
      - qdrant_data:/qdrant/storage
  backend:
    build: ./backend
    env_file: ./backend/.env.example
    depends_on: [ qdrant ]
    ports: [ "8000:8000" ]
    volumes:
      - ./data:/app/data
  frontend:
    build: ./frontend
    depends_on: [ backend ]
    ports: [ "80:80" ]
volumes:
  qdrant_data:
